/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { GetApiGithubCallbackParams } from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Redirects user to GitHub for OAuth2 authorization.
 * @summary Initiate GitHub OAuth2 Authorization
 */
export const getApiGithubAuthorize = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.get(`/api/github/authorize`, options);
};

export const getGetApiGithubAuthorizeQueryKey = () => {
  return [`/api/github/authorize`] as const;
};

export const getGetApiGithubAuthorizeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiGithubAuthorize>>,
  TError = AxiosError<void | void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getApiGithubAuthorize>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiGithubAuthorizeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiGithubAuthorize>>
  > = ({ signal }) => getApiGithubAuthorize({ signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiGithubAuthorize>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiGithubAuthorizeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiGithubAuthorize>>
>;
export type GetApiGithubAuthorizeQueryError = AxiosError<void | void>;

export function useGetApiGithubAuthorize<
  TData = Awaited<ReturnType<typeof getApiGithubAuthorize>>,
  TError = AxiosError<void | void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubAuthorize>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGithubAuthorize>>,
          TError,
          Awaited<ReturnType<typeof getApiGithubAuthorize>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiGithubAuthorize<
  TData = Awaited<ReturnType<typeof getApiGithubAuthorize>>,
  TError = AxiosError<void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubAuthorize>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGithubAuthorize>>,
          TError,
          Awaited<ReturnType<typeof getApiGithubAuthorize>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiGithubAuthorize<
  TData = Awaited<ReturnType<typeof getApiGithubAuthorize>>,
  TError = AxiosError<void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubAuthorize>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Initiate GitHub OAuth2 Authorization
 */

export function useGetApiGithubAuthorize<
  TData = Awaited<ReturnType<typeof getApiGithubAuthorize>>,
  TError = AxiosError<void | void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubAuthorize>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiGithubAuthorizeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Handles the OAuth2 callback from GitHub and processes the authorization code.
 * @summary Handle GitHub OAuth2 Callback
 */
export const getApiGithubCallback = (
  params: GetApiGithubCallbackParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.get(`/api/github/callback`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiGithubCallbackQueryKey = (
  params?: GetApiGithubCallbackParams,
) => {
  return [`/api/github/callback`, ...(params ? [params] : [])] as const;
};

export const getGetApiGithubCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiGithubCallback>>,
  TError = AxiosError<void | void>,
>(
  params: GetApiGithubCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubCallback>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiGithubCallbackQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiGithubCallback>>
  > = ({ signal }) => getApiGithubCallback(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiGithubCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiGithubCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiGithubCallback>>
>;
export type GetApiGithubCallbackQueryError = AxiosError<void | void>;

export function useGetApiGithubCallback<
  TData = Awaited<ReturnType<typeof getApiGithubCallback>>,
  TError = AxiosError<void | void>,
>(
  params: GetApiGithubCallbackParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGithubCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiGithubCallback>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiGithubCallback<
  TData = Awaited<ReturnType<typeof getApiGithubCallback>>,
  TError = AxiosError<void | void>,
>(
  params: GetApiGithubCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubCallback>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGithubCallback>>,
          TError,
          Awaited<ReturnType<typeof getApiGithubCallback>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiGithubCallback<
  TData = Awaited<ReturnType<typeof getApiGithubCallback>>,
  TError = AxiosError<void | void>,
>(
  params: GetApiGithubCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubCallback>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Handle GitHub OAuth2 Callback
 */

export function useGetApiGithubCallback<
  TData = Awaited<ReturnType<typeof getApiGithubCallback>>,
  TError = AxiosError<void | void>,
>(
  params: GetApiGithubCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiGithubCallback>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiGithubCallbackQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
