import { REASONS, ROLE_MEMBERS, SEVERITIES, STATES, WORKITEMTYPE } from '@/constants/common.constants';
import { z } from 'zod';
import mongoose from 'mongoose'

export const objectId = z.string().refine(
    value => mongoose.Types.ObjectId.isValid(value),
    value => ({ message: `${value} is not a valid MongoDB ObjectId` }),
)

// User validation schemas
export const userSchema = z.object({
    name: z.string().min(1, 'Name is required').max(100),
    email: z.string().email('Invalid email format').toLowerCase(),
    password: z.string().min(6, 'Password must be at least 6 characters'),
    role: z.enum(['user', 'admin', 'moderator']).default('user'),
    isFromEMS: z.boolean().default(false),
    autoGeneratedPassword: z.boolean().default(false),
    githubUsername: z.string().nullable().optional(),
    githubAccessToken: z.string().nullable().optional(),
    githubId: z.number().nullable().optional(),
    userId: z.string().nullable().optional()
});

export const createUserSchema = userSchema.omit({
    autoGeneratedPassword: true,
    isFromEMS: true,
    githubUsername: true,
    githubAccessToken: true,
    githubId: true,
    userId: true
});

export const updateUserSchema = userSchema.partial().omit({
    password: true // Password updates should be separate
});

export const loginSchema = z.object({
    email: z.string().email('Invalid email format').toLowerCase(),
    password: z.string().min(1, 'Password is required')
});

export const changePasswordSchema = z.object({
    currentPassword: z.string().min(1, 'Current password is required'),
    newPassword: z.string().min(6, 'New password must be at least 6 characters'),
    confirmPassword: z.string().min(1, 'Password confirmation is required')
}).refine((data) => data.newPassword === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"]
});

export const emsUserSchema = z.object({
    name: z.string().min(1, 'Name is required').max(100),
    email: z.string().email('Invalid email format').toLowerCase(),
    role: z.enum(['user', 'admin', 'moderator']).default('user'),
    userId: z.string().min(1, 'User ID is required'),
    githubUsername: z.string().nullable().optional(),
});

export const githubUserSchema = z.object({
    githubUsername: z.string().min(1, 'GitHub username is required'),
    githubAccessToken: z.string().min(1, 'GitHub access token is required'),
    githubId: z.number().positive('GitHub ID must be positive')
});

export const projectSchema = z.object({
    projectId: z.string().optional(), // Auto-generated if not provided
    title: z.string().min(1, 'Title is required').max(100),
    description: z.string().trim().optional(),
    projectCreatorId: z.string().min(1, 'Project creator ID is required'),
    favourite: z.boolean().default(false),
    status: z.enum(['active', 'completed', 'on-hold']).default('active'),
    startDate: z.date().optional().or(z.string().datetime().optional()),
    endDate: z.date().optional().or(z.string().datetime().optional()),
    assignedRepos: z.array(z.string()).default([]),
    about: z.enum(['readme', 'wiki']).default('readme'),
    tags: z.array(z.string()).max(10, 'Maximum 10 tags allowed').default([]),
    liveUrl: z.string().url().optional().or(z.literal('')),
    images: z.array(z.string().url()).optional(),
    featured: z.boolean().default(false),
    technologies: z.array(z.string()).default([]),
    members: z.array(z.string()).default([]),
    likes: z.array(z.string()).default([]),
    createdFromEMS: z.boolean().default(false)
});

export const createProjectSchema = projectSchema.omit({
    projectId: true,
    createdFromEMS: true,
    likes: true
});

export const updateProjectSchema = projectSchema.partial().omit({
    projectId: true,
    projectCreatorId: true,
    createdFromEMS: true
});

export const emsProjectSchema = z.object({
    title: z.string().min(1, 'Title is required').max(100),
    description: z.string().trim().optional(),
    projectCreatorId: z.string().min(1, 'Project creator ID is required'),
    status: z.enum(['active', 'completed', 'on-hold']).default('active'),
    startDate: z.date().optional().or(z.string().datetime().optional()),
    endDate: z.date().optional().or(z.string().datetime().optional()),
    technologies: z.array(z.string()).default([]),
    tags: z.array(z.string()).max(10, 'Maximum 10 tags allowed').default([]),
    members: z.array(z.string()).default([]),
});

export const projectFilterSchema = z.object({
    status: z.enum(['active', 'completed', 'on-hold']).optional(),
    featured: z.boolean().optional(),
    createdFromEMS: z.boolean().optional(),
    projectCreatorId: z.string().optional(),
    search: z.string().optional(),
    technologies: z.array(z.string()).optional(),
    tags: z.array(z.string()).optional(),
    startDate: z.date().optional().or(z.string().datetime().optional()),
    endDate: z.date().optional().or(z.string().datetime().optional())
});

export const projectMemberSchema = z.object({
    userId: z.string().min(1, 'User ID is required'),
    action: z.enum(['add', 'remove'])
});

export const updateProjectMemberSchema = z.object({
    oldUserId: z.string().min(1, 'Old User ID is required'),
    newUserId: z.string().min(1, 'New User ID is required'),
    action: z.literal('update')
});

export const projectLikeSchema = z.object({
    userId: z.string().min(1, 'User ID is required')
});

// Legacy schema for backward compatibility - keeping the old name
export const legacyProjectSchema = z.object({
    title: z.string().min(1, 'Title is required').max(100),
    user_id: z.string().min(1, 'User ID is required').max(100),
    status: z.enum(['active', 'completed', 'on-hold']).default('active'),
    favorite: z.boolean().optional().default(false),
    description: z.string().optional(),
    startDate: z.string().datetime().optional(),
    endDate: z.string().datetime().optional(),
    repository: z.string().url().optional(),
    liveUrl: z.string().url().optional(),
    images: z.array(z.string().url()).optional(),
    featured: z.boolean().optional().default(false),
    technologies: z.array(z.string()).optional(),
});


export const workItemCommentSchema = z.object({
    comment: z.string().min(1, "Comment is required").max(50000, "Comment cannot exceed 50000 characters"),
    workItemId: objectId.describe("Work Item ID is required"),
    reactions: z.array(z.string()).optional(),
    createdBy: objectId.describe("Creator ID is required"),
});

export const createWorkItemCommentSchema = workItemCommentSchema.omit({
    workItemId: true,
    createdBy: true,
    reactions: true
});

// Work Item Schema Validations
export const workItemSchema = z.object({
    // --- CORE IDENTITY ---
    number: z.number().positive('Number must be positive').optional(), // Auto-generated
    title: z.string().trim().min(1, 'Title is required').max(200, 'Title cannot exceed 200 characters'),
    type: z.enum(Object.values(WORKITEMTYPE)).describe('Type is required'),
    description: z.string().trim().max(50000).optional().describe('Description is optional'),

    // --- WORKFLOW & STATE ---
    state: z.enum(Object.values(STATES)).default('To Do'),
    reason: z.enum(Object.values(REASONS)).default('Added To Backlog'),

    // --- PEOPLE ---
    assignedTo: objectId.optional().nullable().describe('Assigned To is optional'),
    createdBy: objectId.describe('Creator ID is required'),
    updatedBy: objectId.describe('Updated By ID is required'),

    // --- LOCATION & HIERARCHY ---
    project: objectId.describe('Project ID is required'),
    repo: objectId.describe('Repository ID is required'),
    area: z.string().trim().min(1, 'Area is required').max(100, 'Area cannot exceed 100 characters'),
    iteration: z.string().trim().min(1, 'Iteration is required').max(100, 'Iteration cannot exceed 100 characters'),
    parentId: objectId.optional().nullable().describe('Parent ID for hierarchy'),

    // --- PLANNING ---
    startDate: z.date().optional().or(z.string().datetime().optional()),
    targetDate: z.date().optional().or(z.string().datetime().optional()),
    priority: z.number().int().min(1).max(4).default(2).describe('Priority (1-4)'),

    activity: z.string().trim().max(1000).optional(),
    remainingWork: z.number().optional(),
    effort: z.number().optional(),

    dueDate: z.date().optional().or(z.string().datetime().optional()),

    // --- METADATA ---
    tags: z.array(z.string().trim().max(50)).default([]),
    labels: z.array(z.string().trim().max(50)).default([]),

    stackRank: z.number().min(0).optional(),
    severity: z.number().int().min(1).max(3).default(2),

    isArchived: z.boolean().optional().default(false),
    position:z.string().optional(),
});

export const createWorkItemSchema = workItemSchema.omit({
    number: true,
})

export const updateWorkItemSchema = workItemSchema.partial().omit({
    number: true,
    createdBy: true // Cannot change creator,
});

export const workItemFilterSchema = z.object({
    type: z.enum(['Feature', 'Bug', 'Enhancement', 'Documentation', 'Task', 'Epic', 'Test Case', 'Issue', 'User Story']).optional(),
    status: z.enum(['todo', 'in-progress', 'review', 'doing', 'completed', 'active', 'new', 'resolved']).optional(),
    priority: z.number().int().min(1).max(4).optional(),
    assignee: z.string().optional(),
    assignedTo: z.string().optional(),
    project: z.string().optional(),
    area: z.string().optional(),
    iteration: z.string().optional(),
    risk: z.number().int().min(1).max(3).optional(),
    state: z.enum(['New', 'Active', 'Closed', 'Resolved']).optional(),
    severity: z.enum(['1 - High', '2 - Medium', '3 - Low']).optional(),
    tags: z.array(z.string()).optional(),
    labels: z.array(z.string()).optional(),
    search: z.string().optional(),
    startDate: z.date().optional().or(z.string().datetime().optional()),
    targetDate: z.date().optional().or(z.string().datetime().optional()),
    dueDate: z.date().optional().or(z.string().datetime().optional())
});


export const workItemAssignmentSchema = z.object({
    assignedTo: z.string().min(1, 'Assignee ID is required'),
    assignee: z.string().optional() // For backward compatibility
});

export const workItemStatusSchema = z.object({
    status: z.enum(['todo', 'in-progress', 'review', 'doing', 'completed', 'active', 'new', 'resolved']),
    state: z.enum(['New', 'Active', 'Closed', 'Resolved']).optional()
});

export const reorderWorkItemSchema = z.object({
    project: objectId.describe('Project ID is required'),
    repo: objectId.describe('Repository ID is required'),
    workItemId: objectId.describe('Work Item ID is required'),
    parentId: objectId.optional().nullable().describe("Parent ID must be mongodb Object ID"),
    prevRank: z.string().optional().nullable().describe('Stack rank of the item above (LexoRank format)'),
    nextRank: z.string().optional().nullable().describe('Stack rank of the item below (LexoRank format)'),
    status:z.string().optional(),
    state:z.string().optional()
});

export const workItemPullRequestSchema = z.object({
    url: z.string().url('Invalid URL format'),
    status: z.enum(['open', 'merged', 'closed']),
    number: z.number().positive('Pull request number must be positive')
});

// Legacy schema for backward compatibility
export const legacyWorkItemSchema = z.object({
    title: z.string().min(1, 'Title is required').max(200),
    description: z.string().min(1, 'Description is required'),
    number: z.number(),
    createdBy: z.string(),
    type: z.enum(['feature', 'bug', 'enhancement', 'documentation', 'epic', 'story']),
    status: z.enum(['todo', 'in-progress', 'review', 'completed', 'new', 'active', 'resolved', 'closed']),
    priority: z.enum(['low', 'medium', 'high', 'urgent']).default('medium'),
    assignee: z.string().min(1, 'Assignee is required'),
    project: z.string().min(1, 'Project ID is required'),
    user_id: z.string().min(1, 'User ID is required').max(100),
    pullRequest: z.object({
        url: z.string().url().optional(),
        status: z.enum(['open', 'merged', 'closed']).optional(),
        number: z.number().optional()
    }).optional(),
    labels: z.array(z.string()).optional(),
    dueDate: z.string().datetime().optional()
});

// Repository schemas
export const repoSchema = z.object({
    name: z.string().min(1, 'Repository name is required').max(255),
    description: z.string().max(500).optional(),
    githubRepoId: z.number().min(1, 'GitHub Repository ID is required'),
    defaultBranch: z.string().default('main').optional(),
    projectId: z.string().min(1, 'Project ID is required'),
    createdFromEMS: z.boolean().default(false).optional(),
    url: z.string().url().optional(),
    clone_url: z.string().url().optional(),
    ssh_url: z.string().optional(),
    html_url: z.string().url().optional()
});

export const createRepoSchema = repoSchema.omit({
    createdFromEMS: true
});

export const updateRepoSchema = repoSchema.partial().omit({
    githubRepoId: true,
    projectId: true
});

export const emsRepoSchema = z.object({
    name: z.string().min(1, 'Repository name is required').max(255),
    description: z.string().max(500).optional(),
    githubRepoId: z.number().min(1, 'GitHub Repository ID is required'),
    defaultBranch: z.string().default('main').optional(),
    isPrivate: z.boolean().default(true).optional(),
    projectId: z.string().min(1, 'Project ID is required'),
    repoCreatorId: z.string().min(1, 'Repository creator ID is required'),
    members: z.array(z.string()).default([]),
    url: z.string().url().optional(),
});

export const repoMemberSchema = z.object({
    userId: z.string().min(1, 'User ID is required'),
    action: z.enum(['add', 'remove'])
});

export const updateRepoMemberSchema = z.object({
    oldUserId: z.string().min(1, 'Old User ID is required'),
    newUserId: z.string().min(1, 'New User ID is required'),
    action: z.literal('update')
});

export const updateRoleMemberSchema = z.object({
    userId: z.string().min(1, 'User ID is required', { required_error: 'User ID is required', invalid_type_error: 'User ID must be a string' }),
    role: z.enum(Object.values(ROLE_MEMBERS), { required_error: 'Role is required', invalid_type_error: 'Role must be scrumMaster or departmentLead' })
})