/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ApiResponse,
  CreateWorkItemBody,
  GetApiWorkItemsParams,
  GetApiWorkItemsSearchParams,
  GetBacklogWorkItems200,
  GetBacklogWorkItemsParams,
  GetBoardWorkItems200,
  GetBoardWorkItemsParams,
  GetWorkItemById200,
  GetWorkItemsList200,
  GetWorkItemsListBody,
  PostApiWorkItemsIdAssignBody,
  ReorderWorkItem200,
  ReorderWorkItemBody,
  WorkItem,
} from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get work items
 */
export const getApiWorkItems = (
  params?: GetApiWorkItemsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/work-items`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiWorkItemsQueryKey = (params?: GetApiWorkItemsParams) => {
  return [`/api/work-items`, ...(params ? [params] : [])] as const;
};

export const getGetApiWorkItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiWorkItems>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiWorkItemsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiWorkItems>>> = ({
    signal,
  }) => getApiWorkItems(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiWorkItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiWorkItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiWorkItems>>
>;
export type GetApiWorkItemsQueryError = AxiosError<unknown>;

export function useGetApiWorkItems<
  TData = Awaited<ReturnType<typeof getApiWorkItems>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | GetApiWorkItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiWorkItems<
  TData = Awaited<ReturnType<typeof getApiWorkItems>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiWorkItems<
  TData = Awaited<ReturnType<typeof getApiWorkItems>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work items
 */

export function useGetApiWorkItems<
  TData = Awaited<ReturnType<typeof getApiWorkItems>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiWorkItemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a new work item with the specified details
 * @summary Create work item
 */
export const createWorkItem = (
  createWorkItemBody: CreateWorkItemBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(`/api/work-items`, createWorkItemBody, options);
};

export const getCreateWorkItemMutationOptions = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWorkItem>>,
    TError,
    { data: CreateWorkItemBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWorkItem>>,
  TError,
  { data: CreateWorkItemBody },
  TContext
> => {
  const mutationKey = ["createWorkItem"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWorkItem>>,
    { data: CreateWorkItemBody }
  > = (props) => {
    const { data } = props ?? {};

    return createWorkItem(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWorkItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWorkItem>>
>;
export type CreateWorkItemMutationBody = CreateWorkItemBody;
export type CreateWorkItemMutationError = AxiosError<void | void | void>;

/**
 * @summary Create work item
 */
export const useCreateWorkItem = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWorkItem>>,
      TError,
      { data: CreateWorkItemBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWorkItem>>,
  TError,
  { data: CreateWorkItemBody },
  TContext
> => {
  const mutationOptions = getCreateWorkItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a paginated list of work items with advanced filtering options
 * @summary Get work items list with filters
 */
export const getWorkItemsList = (
  getWorkItemsListBody: GetWorkItemsListBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetWorkItemsList200>> => {
  return axios.default.patch(`/api/work-items`, getWorkItemsListBody, options);
};

export const getGetWorkItemsListMutationOptions = <
  TError = AxiosError<void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getWorkItemsList>>,
    TError,
    { data: GetWorkItemsListBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getWorkItemsList>>,
  TError,
  { data: GetWorkItemsListBody },
  TContext
> => {
  const mutationKey = ["getWorkItemsList"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getWorkItemsList>>,
    { data: GetWorkItemsListBody }
  > = (props) => {
    const { data } = props ?? {};

    return getWorkItemsList(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetWorkItemsListMutationResult = NonNullable<
  Awaited<ReturnType<typeof getWorkItemsList>>
>;
export type GetWorkItemsListMutationBody = GetWorkItemsListBody;
export type GetWorkItemsListMutationError = AxiosError<void | void>;

/**
 * @summary Get work items list with filters
 */
export const useGetWorkItemsList = <
  TError = AxiosError<void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getWorkItemsList>>,
      TError,
      { data: GetWorkItemsListBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getWorkItemsList>>,
  TError,
  { data: GetWorkItemsListBody },
  TContext
> => {
  const mutationOptions = getGetWorkItemsListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves parent work items with nested children (sub-items) for Kanban board view. Returns minimal fields optimized for board display.
 * @summary Get work items for Kanban board
 */
export const getBoardWorkItems = (
  params: GetBoardWorkItemsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetBoardWorkItems200>> => {
  return axios.default.get(`/api/work-items/board`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetBoardWorkItemsQueryKey = (
  params?: GetBoardWorkItemsParams,
) => {
  return [`/api/work-items/board`, ...(params ? [params] : [])] as const;
};

export const getGetBoardWorkItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBoardWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBoardWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBoardWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBoardWorkItemsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBoardWorkItems>>
  > = ({ signal }) => getBoardWorkItems(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBoardWorkItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBoardWorkItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBoardWorkItems>>
>;
export type GetBoardWorkItemsQueryError = AxiosError<void | void | void>;

export function useGetBoardWorkItems<
  TData = Awaited<ReturnType<typeof getBoardWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBoardWorkItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBoardWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBoardWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getBoardWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBoardWorkItems<
  TData = Awaited<ReturnType<typeof getBoardWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBoardWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBoardWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBoardWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getBoardWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBoardWorkItems<
  TData = Awaited<ReturnType<typeof getBoardWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBoardWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBoardWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work items for Kanban board
 */

export function useGetBoardWorkItems<
  TData = Awaited<ReturnType<typeof getBoardWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBoardWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBoardWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBoardWorkItemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Retrieves parent work items with nested children (sub-items) for Kanban backlog view. Returns minimal fields optimized for board display.
 * @summary Get work items for Kanban board
 */
export const getBacklogWorkItems = (
  params: GetBacklogWorkItemsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetBacklogWorkItems200>> => {
  return axios.default.get(`/api/work-items/backlogs`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetBacklogWorkItemsQueryKey = (
  params?: GetBacklogWorkItemsParams,
) => {
  return [`/api/work-items/backlogs`, ...(params ? [params] : [])] as const;
};

export const getGetBacklogWorkItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBacklogWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBacklogWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBacklogWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBacklogWorkItemsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBacklogWorkItems>>
  > = ({ signal }) => getBacklogWorkItems(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBacklogWorkItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBacklogWorkItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBacklogWorkItems>>
>;
export type GetBacklogWorkItemsQueryError = AxiosError<void | void | void>;

export function useGetBacklogWorkItems<
  TData = Awaited<ReturnType<typeof getBacklogWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBacklogWorkItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBacklogWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBacklogWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getBacklogWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBacklogWorkItems<
  TData = Awaited<ReturnType<typeof getBacklogWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBacklogWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBacklogWorkItems>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBacklogWorkItems>>,
          TError,
          Awaited<ReturnType<typeof getBacklogWorkItems>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBacklogWorkItems<
  TData = Awaited<ReturnType<typeof getBacklogWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBacklogWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBacklogWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work items for Kanban board
 */

export function useGetBacklogWorkItems<
  TData = Awaited<ReturnType<typeof getBacklogWorkItems>>,
  TError = AxiosError<void | void | void>,
>(
  params: GetBacklogWorkItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBacklogWorkItems>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBacklogWorkItemsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Reorders a work item by updating its stack rank based on surrounding items. Uses LexoRank algorithm to calculate the new position between prevRank and nextRank.
 * @summary Reorder work item in backlog
 */
export const reorderWorkItem = (
  reorderWorkItemBody: ReorderWorkItemBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ReorderWorkItem200>> => {
  return axios.default.patch(
    `/api/work-items/reorder`,
    reorderWorkItemBody,
    options,
  );
};

export const getReorderWorkItemMutationOptions = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof reorderWorkItem>>,
    TError,
    { data: ReorderWorkItemBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof reorderWorkItem>>,
  TError,
  { data: ReorderWorkItemBody },
  TContext
> => {
  const mutationKey = ["reorderWorkItem"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof reorderWorkItem>>,
    { data: ReorderWorkItemBody }
  > = (props) => {
    const { data } = props ?? {};

    return reorderWorkItem(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ReorderWorkItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof reorderWorkItem>>
>;
export type ReorderWorkItemMutationBody = ReorderWorkItemBody;
export type ReorderWorkItemMutationError = AxiosError<
  void | void | void | void
>;

/**
 * @summary Reorder work item in backlog
 */
export const useReorderWorkItem = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof reorderWorkItem>>,
      TError,
      { data: ReorderWorkItemBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof reorderWorkItem>>,
  TError,
  { data: ReorderWorkItemBody },
  TContext
> => {
  const mutationOptions = getReorderWorkItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a single work item by its ID with populated project, createdBy, and assignedTo fields
 * @summary Get work item by ID
 */
export const getWorkItemById = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetWorkItemById200>> => {
  return axios.default.get(`/api/work-items/${id}`, options);
};

export const getGetWorkItemByIdQueryKey = (id?: string) => {
  return [`/api/work-items/${id}`] as const;
};

export const getGetWorkItemByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkItemById>>,
  TError = AxiosError<void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemById>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWorkItemByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkItemById>>> = ({
    signal,
  }) => getWorkItemById(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkItemById>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkItemByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkItemById>>
>;
export type GetWorkItemByIdQueryError = AxiosError<void | void>;

export function useGetWorkItemById<
  TData = Awaited<ReturnType<typeof getWorkItemById>>,
  TError = AxiosError<void | void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemById>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkItemById>>,
          TError,
          Awaited<ReturnType<typeof getWorkItemById>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkItemById<
  TData = Awaited<ReturnType<typeof getWorkItemById>>,
  TError = AxiosError<void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemById>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkItemById>>,
          TError,
          Awaited<ReturnType<typeof getWorkItemById>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkItemById<
  TData = Awaited<ReturnType<typeof getWorkItemById>>,
  TError = AxiosError<void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemById>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get work item by ID
 */

export function useGetWorkItemById<
  TData = Awaited<ReturnType<typeof getWorkItemById>>,
  TError = AxiosError<void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemById>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkItemByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update work item
 */
export const updateWorkItem = (
  id: string,
  workItem: WorkItem,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.put(`/api/work-items/${id}`, workItem, options);
};

export const getUpdateWorkItemMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWorkItem>>,
    TError,
    { id: string; data: WorkItem },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateWorkItem>>,
  TError,
  { id: string; data: WorkItem },
  TContext
> => {
  const mutationKey = ["updateWorkItem"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateWorkItem>>,
    { id: string; data: WorkItem }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateWorkItem(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateWorkItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateWorkItem>>
>;
export type UpdateWorkItemMutationBody = WorkItem;
export type UpdateWorkItemMutationError = AxiosError<unknown>;

/**
 * @summary Update work item
 */
export const useUpdateWorkItem = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateWorkItem>>,
      TError,
      { id: string; data: WorkItem },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateWorkItem>>,
  TError,
  { id: string; data: WorkItem },
  TContext
> => {
  const mutationOptions = getUpdateWorkItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete work item
 */
export const deleteWorkItem = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.delete(`/api/work-items/${id}`, options);
};

export const getDeleteWorkItemMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWorkItem>>,
    TError,
    { id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWorkItem>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteWorkItem"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWorkItem>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteWorkItem(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWorkItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWorkItem>>
>;

export type DeleteWorkItemMutationError = AxiosError<unknown>;

/**
 * @summary Delete work item
 */
export const useDeleteWorkItem = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteWorkItem>>,
      TError,
      { id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteWorkItem>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteWorkItemMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Assign work item
 */
export const postApiWorkItemsIdAssign = (
  id: string,
  postApiWorkItemsIdAssignBody: PostApiWorkItemsIdAssignBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(
    `/api/work-items/${id}/assign`,
    postApiWorkItemsIdAssignBody,
    options,
  );
};

export const getPostApiWorkItemsIdAssignMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>,
    TError,
    { id: string; data: PostApiWorkItemsIdAssignBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>,
  TError,
  { id: string; data: PostApiWorkItemsIdAssignBody },
  TContext
> => {
  const mutationKey = ["postApiWorkItemsIdAssign"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>,
    { id: string; data: PostApiWorkItemsIdAssignBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiWorkItemsIdAssign(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiWorkItemsIdAssignMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>
>;
export type PostApiWorkItemsIdAssignMutationBody = PostApiWorkItemsIdAssignBody;
export type PostApiWorkItemsIdAssignMutationError = AxiosError<unknown>;

/**
 * @summary Assign work item
 */
export const usePostApiWorkItemsIdAssign = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>,
      TError,
      { id: string; data: PostApiWorkItemsIdAssignBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiWorkItemsIdAssign>>,
  TError,
  { id: string; data: PostApiWorkItemsIdAssignBody },
  TContext
> => {
  const mutationOptions = getPostApiWorkItemsIdAssignMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Search work items
 */
export const getApiWorkItemsSearch = (
  params?: GetApiWorkItemsSearchParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/work-items/search`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiWorkItemsSearchQueryKey = (
  params?: GetApiWorkItemsSearchParams,
) => {
  return [`/api/work-items/search`, ...(params ? [params] : [])] as const;
};

export const getGetApiWorkItemsSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiWorkItemsSearchQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiWorkItemsSearch>>
  > = ({ signal }) =>
    getApiWorkItemsSearch(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiWorkItemsSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiWorkItemsSearch>>
>;
export type GetApiWorkItemsSearchQueryError = AxiosError<unknown>;

export function useGetApiWorkItemsSearch<
  TData = Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | GetApiWorkItemsSearchParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkItemsSearch>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiWorkItemsSearch<
  TData = Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiWorkItemsSearch>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiWorkItemsSearch<
  TData = Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search work items
 */

export function useGetApiWorkItemsSearch<
  TData = Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiWorkItemsSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiWorkItemsSearch>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiWorkItemsSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
