/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ApiResponse,
  GetApiProjectsParams,
  PostApiProjectsBody,
  Project,
  UpdateProjectTitleBody,
} from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get projects
 */
export const getApiProjects = (
  params?: GetApiProjectsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/projects`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiProjectsQueryKey = (params?: GetApiProjectsParams) => {
  return [`/api/projects`, ...(params ? [params] : [])] as const;
};

export const getGetApiProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProjects>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiProjectsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiProjects>>> = ({
    signal,
  }) => getApiProjects(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProjects>>
>;
export type GetApiProjectsQueryError = AxiosError<unknown>;

export function useGetApiProjects<
  TData = Awaited<ReturnType<typeof getApiProjects>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | GetApiProjectsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProjects>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiProjects>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProjects<
  TData = Awaited<ReturnType<typeof getApiProjects>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProjects>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProjects>>,
          TError,
          Awaited<ReturnType<typeof getApiProjects>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProjects<
  TData = Awaited<ReturnType<typeof getApiProjects>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get projects
 */

export function useGetApiProjects<
  TData = Awaited<ReturnType<typeof getApiProjects>>,
  TError = AxiosError<unknown>,
>(
  params?: GetApiProjectsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProjectsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create project
 */
export const postApiProjects = (
  postApiProjectsBody: PostApiProjectsBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(`/api/projects`, postApiProjectsBody, options);
};

export const getPostApiProjectsMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiProjects>>,
    TError,
    { data: PostApiProjectsBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiProjects>>,
  TError,
  { data: PostApiProjectsBody },
  TContext
> => {
  const mutationKey = ["postApiProjects"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiProjects>>,
    { data: PostApiProjectsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiProjects(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiProjectsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiProjects>>
>;
export type PostApiProjectsMutationBody = PostApiProjectsBody;
export type PostApiProjectsMutationError = AxiosError<unknown>;

/**
 * @summary Create project
 */
export const usePostApiProjects = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiProjects>>,
      TError,
      { data: PostApiProjectsBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiProjects>>,
  TError,
  { data: PostApiProjectsBody },
  TContext
> => {
  const mutationOptions = getPostApiProjectsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get project by ID
 */
export const getApiProjectsId = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/projects/${id}`, options);
};

export const getGetApiProjectsIdQueryKey = (id?: string) => {
  return [`/api/projects/${id}`] as const;
};

export const getGetApiProjectsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiProjectsId>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProjectsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiProjectsIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiProjectsId>>
  > = ({ signal }) => getApiProjectsId(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiProjectsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiProjectsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiProjectsId>>
>;
export type GetApiProjectsIdQueryError = AxiosError<unknown>;

export function useGetApiProjectsId<
  TData = Awaited<ReturnType<typeof getApiProjectsId>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProjectsId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProjectsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProjectsId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProjectsId<
  TData = Awaited<ReturnType<typeof getApiProjectsId>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProjectsId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiProjectsId>>,
          TError,
          Awaited<ReturnType<typeof getApiProjectsId>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiProjectsId<
  TData = Awaited<ReturnType<typeof getApiProjectsId>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProjectsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get project by ID
 */

export function useGetApiProjectsId<
  TData = Awaited<ReturnType<typeof getApiProjectsId>>,
  TError = AxiosError<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiProjectsId>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiProjectsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update project
 */
export const putApiProjectsId = (
  id: string,
  project: Project,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.put(`/api/projects/${id}`, project, options);
};

export const getPutApiProjectsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiProjectsId>>,
    TError,
    { id: string; data: Project },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiProjectsId>>,
  TError,
  { id: string; data: Project },
  TContext
> => {
  const mutationKey = ["putApiProjectsId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiProjectsId>>,
    { id: string; data: Project }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiProjectsId(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiProjectsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiProjectsId>>
>;
export type PutApiProjectsIdMutationBody = Project;
export type PutApiProjectsIdMutationError = AxiosError<unknown>;

/**
 * @summary Update project
 */
export const usePutApiProjectsId = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiProjectsId>>,
      TError,
      { id: string; data: Project },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiProjectsId>>,
  TError,
  { id: string; data: Project },
  TContext
> => {
  const mutationOptions = getPutApiProjectsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete project
 */
export const deleteApiProjectsId = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.delete(`/api/projects/${id}`, options);
};

export const getDeleteApiProjectsIdMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiProjectsId>>,
    TError,
    { id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiProjectsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiProjectsId"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiProjectsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiProjectsId(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiProjectsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiProjectsId>>
>;

export type DeleteApiProjectsIdMutationError = AxiosError<unknown>;

/**
 * @summary Delete project
 */
export const useDeleteApiProjectsId = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiProjectsId>>,
      TError,
      { id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiProjectsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteApiProjectsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get project by title
 */
export const getProjectsByTitle = (
  projectTitle: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/projects/title/${projectTitle}`, options);
};

export const getGetProjectsByTitleQueryKey = (projectTitle?: string) => {
  return [`/api/projects/title/${projectTitle}`] as const;
};

export const getGetProjectsByTitleQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjectsByTitle>>,
  TError = AxiosError<unknown>,
>(
  projectTitle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByTitle>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProjectsByTitleQueryKey(projectTitle);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getProjectsByTitle>>
  > = ({ signal }) =>
    getProjectsByTitle(projectTitle, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectTitle,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjectsByTitle>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectsByTitleQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjectsByTitle>>
>;
export type GetProjectsByTitleQueryError = AxiosError<unknown>;

export function useGetProjectsByTitle<
  TData = Awaited<ReturnType<typeof getProjectsByTitle>>,
  TError = AxiosError<unknown>,
>(
  projectTitle: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByTitle>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsByTitle>>,
          TError,
          Awaited<ReturnType<typeof getProjectsByTitle>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsByTitle<
  TData = Awaited<ReturnType<typeof getProjectsByTitle>>,
  TError = AxiosError<unknown>,
>(
  projectTitle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByTitle>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsByTitle>>,
          TError,
          Awaited<ReturnType<typeof getProjectsByTitle>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjectsByTitle<
  TData = Awaited<ReturnType<typeof getProjectsByTitle>>,
  TError = AxiosError<unknown>,
>(
  projectTitle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByTitle>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get project by title
 */

export function useGetProjectsByTitle<
  TData = Awaited<ReturnType<typeof getProjectsByTitle>>,
  TError = AxiosError<unknown>,
>(
  projectTitle: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getProjectsByTitle>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectsByTitleQueryOptions(projectTitle, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update project title
 */
export const updateProjectTitle = (
  projectTitle: string,
  updateProjectTitleBody: UpdateProjectTitleBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.patch(
    `/api/projects/title/${projectTitle}`,
    updateProjectTitleBody,
    options,
  );
};

export const getUpdateProjectTitleMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateProjectTitle>>,
    TError,
    { projectTitle: string; data: UpdateProjectTitleBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateProjectTitle>>,
  TError,
  { projectTitle: string; data: UpdateProjectTitleBody },
  TContext
> => {
  const mutationKey = ["updateProjectTitle"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateProjectTitle>>,
    { projectTitle: string; data: UpdateProjectTitleBody }
  > = (props) => {
    const { projectTitle, data } = props ?? {};

    return updateProjectTitle(projectTitle, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProjectTitleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateProjectTitle>>
>;
export type UpdateProjectTitleMutationBody = UpdateProjectTitleBody;
export type UpdateProjectTitleMutationError = AxiosError<unknown>;

/**
 * @summary Update project title
 */
export const useUpdateProjectTitle = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateProjectTitle>>,
      TError,
      { projectTitle: string; data: UpdateProjectTitleBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateProjectTitle>>,
  TError,
  { projectTitle: string; data: UpdateProjectTitleBody },
  TContext
> => {
  const mutationOptions = getUpdateProjectTitleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
