/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AddCommentReactionBody,
  ApiResponse,
  CreateWorkItemCommentBody,
  GetWorkItemComments200,
  RemoveCommentReactionBody,
  UpdateWorkItemCommentBody,
} from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Retrieves all comments for a specific work item with populated createdBy and reactions.reactedUsers
 * @summary Get comments for a work item
 */
export const getWorkItemComments = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetWorkItemComments200>> => {
  return axios.default.get(`/api/work-items/${id}/comments`, options);
};

export const getGetWorkItemCommentsQueryKey = (id?: string) => {
  return [`/api/work-items/${id}/comments`] as const;
};

export const getGetWorkItemCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getWorkItemComments>>,
  TError = AxiosError<void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemComments>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWorkItemCommentsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWorkItemComments>>
  > = ({ signal }) => getWorkItemComments(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getWorkItemComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWorkItemCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWorkItemComments>>
>;
export type GetWorkItemCommentsQueryError = AxiosError<void | void | void>;

export function useGetWorkItemComments<
  TData = Awaited<ReturnType<typeof getWorkItemComments>>,
  TError = AxiosError<void | void | void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkItemComments>>,
          TError,
          Awaited<ReturnType<typeof getWorkItemComments>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkItemComments<
  TData = Awaited<ReturnType<typeof getWorkItemComments>>,
  TError = AxiosError<void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkItemComments>>,
          TError,
          Awaited<ReturnType<typeof getWorkItemComments>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWorkItemComments<
  TData = Awaited<ReturnType<typeof getWorkItemComments>>,
  TError = AxiosError<void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemComments>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get comments for a work item
 */

export function useGetWorkItemComments<
  TData = Awaited<ReturnType<typeof getWorkItemComments>>,
  TError = AxiosError<void | void | void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWorkItemComments>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWorkItemCommentsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a new comment on the specified work item
 * @summary Create a comment on a work item
 */
export const createWorkItemComment = (
  id: string,
  createWorkItemCommentBody: CreateWorkItemCommentBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(
    `/api/work-items/${id}/comments`,
    createWorkItemCommentBody,
    options,
  );
};

export const getCreateWorkItemCommentMutationOptions = <
  TError = AxiosError<void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWorkItemComment>>,
    TError,
    { id: string; data: CreateWorkItemCommentBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWorkItemComment>>,
  TError,
  { id: string; data: CreateWorkItemCommentBody },
  TContext
> => {
  const mutationKey = ["createWorkItemComment"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWorkItemComment>>,
    { id: string; data: CreateWorkItemCommentBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return createWorkItemComment(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWorkItemCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWorkItemComment>>
>;
export type CreateWorkItemCommentMutationBody = CreateWorkItemCommentBody;
export type CreateWorkItemCommentMutationError = AxiosError<void | void>;

/**
 * @summary Create a comment on a work item
 */
export const useCreateWorkItemComment = <
  TError = AxiosError<void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWorkItemComment>>,
      TError,
      { id: string; data: CreateWorkItemCommentBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWorkItemComment>>,
  TError,
  { id: string; data: CreateWorkItemCommentBody },
  TContext
> => {
  const mutationOptions = getCreateWorkItemCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Updates an existing comment by its ID
 * @summary Update a comment
 */
export const updateWorkItemComment = (
  id: string,
  updateWorkItemCommentBody: UpdateWorkItemCommentBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.put(
    `/api/work-items/${id}/comments`,
    updateWorkItemCommentBody,
    options,
  );
};

export const getUpdateWorkItemCommentMutationOptions = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateWorkItemComment>>,
    TError,
    { id: string; data: UpdateWorkItemCommentBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateWorkItemComment>>,
  TError,
  { id: string; data: UpdateWorkItemCommentBody },
  TContext
> => {
  const mutationKey = ["updateWorkItemComment"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateWorkItemComment>>,
    { id: string; data: UpdateWorkItemCommentBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateWorkItemComment(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateWorkItemCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateWorkItemComment>>
>;
export type UpdateWorkItemCommentMutationBody = UpdateWorkItemCommentBody;
export type UpdateWorkItemCommentMutationError = AxiosError<
  void | void | void | void
>;

/**
 * @summary Update a comment
 */
export const useUpdateWorkItemComment = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateWorkItemComment>>,
      TError,
      { id: string; data: UpdateWorkItemCommentBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateWorkItemComment>>,
  TError,
  { id: string; data: UpdateWorkItemCommentBody },
  TContext
> => {
  const mutationOptions = getUpdateWorkItemCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Deletes a comment by its ID
 * @summary Delete a comment
 */
export const deleteWorkItemComment = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.delete(`/api/work-items/${id}/comments`, options);
};

export const getDeleteWorkItemCommentMutationOptions = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteWorkItemComment>>,
    TError,
    { id: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteWorkItemComment>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteWorkItemComment"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteWorkItemComment>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteWorkItemComment(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteWorkItemCommentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteWorkItemComment>>
>;

export type DeleteWorkItemCommentMutationError = AxiosError<
  void | void | void | void
>;

/**
 * @summary Delete a comment
 */
export const useDeleteWorkItemComment = <
  TError = AxiosError<void | void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteWorkItemComment>>,
      TError,
      { id: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteWorkItemComment>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteWorkItemCommentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Adds a reaction (emoji) to a specific comment
 * @summary Add a reaction to a comment
 */
export const addCommentReaction = (
  id: string,
  addCommentReactionBody: AddCommentReactionBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(
    `/api/work-items/${id}/comments/reactions`,
    addCommentReactionBody,
    options,
  );
};

export const getAddCommentReactionMutationOptions = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof addCommentReaction>>,
    TError,
    { id: string; data: AddCommentReactionBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof addCommentReaction>>,
  TError,
  { id: string; data: AddCommentReactionBody },
  TContext
> => {
  const mutationKey = ["addCommentReaction"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof addCommentReaction>>,
    { id: string; data: AddCommentReactionBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return addCommentReaction(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AddCommentReactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof addCommentReaction>>
>;
export type AddCommentReactionMutationBody = AddCommentReactionBody;
export type AddCommentReactionMutationError = AxiosError<void | void | void>;

/**
 * @summary Add a reaction to a comment
 */
export const useAddCommentReaction = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof addCommentReaction>>,
      TError,
      { id: string; data: AddCommentReactionBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof addCommentReaction>>,
  TError,
  { id: string; data: AddCommentReactionBody },
  TContext
> => {
  const mutationOptions = getAddCommentReactionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Removes a reaction (emoji) from a specific comment
 * @summary Remove a reaction from a comment
 */
export const removeCommentReaction = (
  id: string,
  removeCommentReactionBody: RemoveCommentReactionBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.delete(`/api/work-items/${id}/comments/reactions`, {
    data: removeCommentReactionBody,
    ...options,
  });
};

export const getRemoveCommentReactionMutationOptions = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeCommentReaction>>,
    TError,
    { id: string; data: RemoveCommentReactionBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeCommentReaction>>,
  TError,
  { id: string; data: RemoveCommentReactionBody },
  TContext
> => {
  const mutationKey = ["removeCommentReaction"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeCommentReaction>>,
    { id: string; data: RemoveCommentReactionBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return removeCommentReaction(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveCommentReactionMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeCommentReaction>>
>;
export type RemoveCommentReactionMutationBody = RemoveCommentReactionBody;
export type RemoveCommentReactionMutationError = AxiosError<void | void | void>;

/**
 * @summary Remove a reaction from a comment
 */
export const useRemoveCommentReaction = <
  TError = AxiosError<void | void | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof removeCommentReaction>>,
      TError,
      { id: string; data: RemoveCommentReactionBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof removeCommentReaction>>,
  TError,
  { id: string; data: RemoveCommentReactionBody },
  TContext
> => {
  const mutationOptions = getRemoveCommentReactionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
