/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponseData } from "./apiResponseData";

export interface ApiResponse {
  success?: boolean;
  message?: string;
  data?: ApiResponseData;
  timestamp?: string;
}
