/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { CommentReactionReactedUsersItem } from "./commentReactionReactedUsersItem";

export interface CommentReaction {
  /** Reaction emoji or type */
  reaction?: string;
  /** Users who reacted with this reaction */
  reactedUsers?: CommentReactionReactedUsersItem[];
}
