/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { CreateWorkItemBodyType } from "./createWorkItemBodyType";
import type { CreateWorkItemBodyState } from "./createWorkItemBodyState";
import type { CreateWorkItemBodyReason } from "./createWorkItemBodyReason";

export type CreateWorkItemBody = {
  /**
   * Work item title (required)
   * @minLength 1
   * @maxLength 200
   */
  title: string;
  /** Work item type (required) */
  type: CreateWorkItemBodyType;
  /**
   * Work item description
   * @maxLength 50000
   */
  description?: string;
  /** Work item state */
  state?: CreateWorkItemBodyState;
  /** Work item reason */
  reason?: CreateWorkItemBodyReason;
  /**
   * User ID to assign the work item to
   * @nullable
   */
  assignedTo?: string | null;
  /** Project ID (required) */
  project: string;
  /** Repository ID (required) */
  repo: string;
  /**
   * Area path (defaults to repo name if not provided)
   * @maxLength 100
   */
  area?: string;
  /**
   * Iteration path (defaults to repo name if not provided)
   * @maxLength 100
   */
  iteration?: string;
  /**
   * Parent work item ID for hierarchy
   * @nullable
   */
  parentId?: string | null;
  /** Start date for the work item */
  startDate?: string;
  /** Target completion date */
  targetDate?: string;
  /**
   * Priority level (1-4, where 1 is highest)
   * @minimum 1
   * @maximum 4
   */
  priority?: number;
  /**
   * Activity type
   * @maxLength 1000
   */
  activity?: string;
  /** Remaining work in hours */
  remainingWork?: number;
  /** Effort estimate */
  effort?: number;
  /** Due date for the work item */
  dueDate?: string;
  /** Tags for categorization */
  tags?: string[];
  /** Labels for categorization */
  labels?: string[];
  /**
   * Stack rank for ordering
   * @minimum 0
   */
  stackRank?: number;
  /**
   * Severity level (1-3, where 1 is highest)
   * @minimum 1
   * @maximum 3
   */
  severity?: number;
  /** Whether the work item is archived */
  isArchived?: boolean;
};
