/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type GetApiWorkItemsParams = {
  projectId?: string;
  assignedTo?: string;
  status?: string;
  page?: number;
  limit?: number;
};
