/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type GetApiGithubCallbackParams = {
  /**
   * Authorization code received from GitHub
   */
  code: string;
  /**
   * State parameter to protect against CSRF attacks
   */
  state?: string;
};
