/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItem200AllOfDataWorkItemsItemAssignedUser } from "./getBacklogWorkItem200AllOfDataWorkItemsItemAssignedUser";
import type { GetBacklogWorkItem200AllOfDataWorkItemsItemChildrenItem } from "./getBacklogWorkItem200AllOfDataWorkItemsItemChildrenItem";

export type GetBacklogWorkItem200AllOfDataWorkItemsItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  priority?: number;
  stackRank?: string;
  assignedUser?: GetBacklogWorkItem200AllOfDataWorkItemsItemAssignedUser;
  children?: GetBacklogWorkItem200AllOfDataWorkItemsItemChildrenItem[];
  childrenCount?: number;
};
