/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from "./apiResponse";
import type { GetBoardWorkItems200AllOf } from "./getBoardWorkItems200AllOf";

export type GetBoardWorkItems200 = ApiResponse & GetBoardWorkItems200AllOf;
