/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItems200AllOfDataWorkItemsItemAssignedUser } from "./getBacklogWorkItems200AllOfDataWorkItemsItemAssignedUser";
import type { GetBacklogWorkItems200AllOfDataWorkItemsItemChildrenItem } from "./getBacklogWorkItems200AllOfDataWorkItemsItemChildrenItem";

export type GetBacklogWorkItems200AllOfDataWorkItemsItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  priority?: number;
  stackRank?: string;
  assignedUser?: GetBacklogWorkItems200AllOfDataWorkItemsItemAssignedUser;
  children?: GetBacklogWorkItems200AllOfDataWorkItemsItemChildrenItem[];
  childrenCount?: number;
};
