/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItemsOnly200AllOfDataWorkItemsItem } from "./getBacklogWorkItemsOnly200AllOfDataWorkItemsItem";

export type GetBacklogWorkItemsOnly200AllOfData = {
  workItems?: GetBacklogWorkItemsOnly200AllOfDataWorkItemsItem[];
  total?: number;
};
