/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBoardWorkItems200AllOfDataWorkItemsItem } from "./getBoardWorkItems200AllOfDataWorkItemsItem";

export type GetBoardWorkItems200AllOfData = {
  workItems?: GetBoardWorkItems200AllOfDataWorkItemsItem[];
  total?: number;
};
