/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItemsOnly200AllOfDataWorkItemsItemAssignedUser } from "./getBacklogWorkItemsOnly200AllOfDataWorkItemsItemAssignedUser";
import type { GetBacklogWorkItemsOnly200AllOfDataWorkItemsItemChildrenItem } from "./getBacklogWorkItemsOnly200AllOfDataWorkItemsItemChildrenItem";

export type GetBacklogWorkItemsOnly200AllOfDataWorkItemsItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  priority?: number;
  stackRank?: string;
  assignedUser?: GetBacklogWorkItemsOnly200AllOfDataWorkItemsItemAssignedUser;
  children?: GetBacklogWorkItemsOnly200AllOfDataWorkItemsItemChildrenItem[];
  childrenCount?: number;
};
