/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBoardWorkItems200AllOfDataWorkItemsItemAssignedUser } from "./getBoardWorkItems200AllOfDataWorkItemsItemAssignedUser";
import type { GetBoardWorkItems200AllOfDataWorkItemsItemChildrenItem } from "./getBoardWorkItems200AllOfDataWorkItemsItemChildrenItem";

export type GetBoardWorkItems200AllOfDataWorkItemsItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  priority?: number;
  assignedUser?: GetBoardWorkItems200AllOfDataWorkItemsItemAssignedUser;
  children?: GetBoardWorkItems200AllOfDataWorkItemsItemChildrenItem[];
  childrenCount?: number;
};
