/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from "./apiResponse";
import type { GetBacklogWorkItems200AllOf } from "./getBacklogWorkItems200AllOf";

export type GetBacklogWorkItems200 = ApiResponse & GetBacklogWorkItems200AllOf;
