/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItemState } from "./getBacklogWorkItemState";

export type GetBacklogWorkItemParams = {
  /**
   * Project ID
   */
  project: string;
  /**
   * Repository ID
   */
  repo: string;
  /**
   * Filter by state
   */
  state?: GetBacklogWorkItemState;
  /**
   * Filter by work item type
   */
  type: string;
};
