/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItemsOnlyState } from "./getBacklogWorkItemsOnlyState";

export type GetBacklogWorkItemsOnlyParams = {
  /**
   * Project ID
   */
  project: string;
  /**
   * Repository ID
   */
  repo: string;
  /**
   * Filter by state
   */
  state?: GetBacklogWorkItemsOnlyState;
  /**
   * Filter by work item type
   */
  type: string;
};
