/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItemsState } from "./getBacklogWorkItemsState";

export type GetBacklogWorkItemsParams = {
  /**
   * Project ID
   */
  project: string;
  /**
   * Repository ID
   */
  repo: string;
  /**
   * Filter by state
   */
  state?: GetBacklogWorkItemsState;
  /**
   * Filter by work item type
   */
  type: string;
  /**
   * Filter by work item search
   */
  search: string;
  /**
   * Filter by area paths
   */
  area?: string[];
  /**
   * Tag operator
   */
  tagOperator?: string;
  /**
   * Tags list to be filtered
   */
  tags?: string[];
  /**
   * Show in progress items also
   */
  inProgressItems?: boolean;
  /**
   * Show completed child items also
   */
  completedChildItems?: boolean;
  /**
   * Keep hierarchy with filters
   */
  keepHierarchyWithFilters?: boolean;
};
