/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from "./apiResponse";
import type { GetBacklogWorkItemsOnly200AllOf } from "./getBacklogWorkItemsOnly200AllOf";

export type GetBacklogWorkItemsOnly200 = ApiResponse &
  GetBacklogWorkItemsOnly200AllOf;
