/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type GetBacklogWorkItemsOnlyState =
  (typeof GetBacklogWorkItemsOnlyState)[keyof typeof GetBacklogWorkItemsOnlyState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetBacklogWorkItemsOnlyState = {
  To_Do: "To Do",
  Doing: "Doing",
  Done: "Done",
} as const;
