/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBoardWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser } from "./getBoardWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser";

export type GetBoardWorkItems200AllOfDataWorkItemsItemChildrenItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  parentId?: string;
  assignedUser?: GetBoardWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser;
};
