/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser } from "./getBacklogWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser";

export type GetBacklogWorkItems200AllOfDataWorkItemsItemChildrenItem = {
  id?: string;
  number?: number;
  title?: string;
  type?: string;
  state?: string;
  parentId?: string;
  assignedUser?: GetBacklogWorkItems200AllOfDataWorkItemsItemChildrenItemAssignedUser;
  stackRank?: string;
};
