/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBacklogWorkItems200AllOfDataWorkItemsItem } from "./getBacklogWorkItems200AllOfDataWorkItemsItem";

export type GetBacklogWorkItems200AllOfData = {
  workItems?: GetBacklogWorkItems200AllOfDataWorkItemsItem[];
  total?: number;
};
