/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetBoardWorkItemsStateItem } from "./getBoardWorkItemsStateItem";

export type GetBoardWorkItemsParams = {
  /**
   * Project ID
   */
  project: string;
  /**
   * Repository ID
   */
  repo: string;
  /**
   * Filter by states
   */
  state?: GetBoardWorkItemsStateItem[];
  /**
   * Filter by work item search
   */
  search: string;
  /**
   * Filter by area paths
   */
  area?: string[];
  /**
   * Tag operator
   */
  tagOperator?: string;
  /**
   * Tags list to be filtered
   */
  tags?: string[];
  /**
   * Filter by work item type
   */
  type: string;
  /**
   * Filter by assigned users
   */
  assignedUsers?: string[];
};
