/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from "./apiResponse";
import type { GetWorkItemsList200AllOf } from "./getWorkItemsList200AllOf";

export type GetWorkItemsList200 = ApiResponse & GetWorkItemsList200AllOf;
