/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

/**
 * Work item type
 */
export type GetWorkItemsListBodyType =
  (typeof GetWorkItemsListBodyType)[keyof typeof GetWorkItemsListBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorkItemsListBodyType = {
  Task: "Task",
  Epic: "Epic",
  Issue: "Issue",
} as const;
