/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

/**
 * Sort direction
 */
export type GetWorkItemsListBodySortOrder =
  (typeof GetWorkItemsListBodySortOrder)[keyof typeof GetWorkItemsListBodySortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorkItemsListBodySortOrder = {
  asc: "asc",
  desc: "desc",
} as const;
