/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { GetWorkItemsListBodyStatus } from "./getWorkItemsListBodyStatus";
import type { GetWorkItemsListBodyState } from "./getWorkItemsListBodyState";
import type { GetWorkItemsListBodyType } from "./getWorkItemsListBodyType";
import type { GetWorkItemsListBodySortOrder } from "./getWorkItemsListBodySortOrder";
import type { GetWorkItemsListBodyPagination } from "./getWorkItemsListBodyPagination";

export type GetWorkItemsListBody = {
  /** Project ID (required) */
  project: string;
  /** Repository ID (required) */
  repo: string;
  /** Filter by assigned user ID */
  assignedTo?: string;
  /** Search term for title, description, tags, labels */
  search?: string;
  /** Filter type for work items */
  status?: GetWorkItemsListBodyStatus;
  /** Work item state */
  state?: GetWorkItemsListBodyState;
  /** Work item type */
  type?: GetWorkItemsListBodyType;
  /** Filter by area paths */
  area?: string[];
  /** Filter by tags */
  tags?: string[];
  /** Field to sort by */
  sortBy?: string;
  /** Sort direction */
  sortOrder?: GetWorkItemsListBodySortOrder;
  pagination?: GetWorkItemsListBodyPagination;
};
