/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

/**
 * Filter type for work items
 */
export type GetWorkItemsListBodyStatus =
  (typeof GetWorkItemsListBodyStatus)[keyof typeof GetWorkItemsListBodyStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetWorkItemsListBodyStatus = {
  assignedToMe: "assignedToMe",
  following: "following",
  mentioned: "mentioned",
  myActivity: "myActivity",
  recentlyUpdated: "recentlyUpdated",
  recentlyCompleted: "recentlyCompleted",
  recentlyCreated: "recentlyCreated",
} as const;
