/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponse } from "./apiResponse";
import type { GetWorkItemComments200AllOf } from "./getWorkItemComments200AllOf";

export type GetWorkItemComments200 = ApiResponse & GetWorkItemComments200AllOf;
