/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type ReorderWorkItemBody = {
  /** Project ID (required) */
  project: string;
  /** Repository ID (required) */
  repo: string;
  /** Work item ID to reorder (required) */
  workItemId: string;
  /**
   * Stack rank of the item above the new position (null if moving to top)
   * @nullable
   */
  prevRank?: string | null;
  /**
   * Stack rank of the item below the new position (null if moving to bottom)
   * @nullable
   */
  nextRank?: string | null;
};
