/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { ReorderWorkItem200AllOfData } from "./reorderWorkItem200AllOfData";

export type ReorderWorkItem200AllOf = {
  data?: ReorderWorkItem200AllOfData;
};
