/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

/**
 * Work item reason
 */
export type UpdateWorkItemBodyReason =
  (typeof UpdateWorkItemBodyReason)[keyof typeof UpdateWorkItemBodyReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateWorkItemBodyReason = {
  Added_To_Backlog: "Added To Backlog",
  New: "New",
  Moved_to_Backlog: "Moved to Backlog",
  Moved_Out_of_Backlog: "Moved Out of Backlog",
  Implementation_Started: "Implementation Started",
  In_Progress: "In Progress",
  Completed: "Completed",
  Duplicate: "Duplicate",
  Resolved: "Resolved",
  Fixed: "Fixed",
  Cancelled: "Cancelled",
  As_Designed: "As Designed",
} as const;
