/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

/**
 * Work item type (required)
 */
export type UpdateWorkItemBodyType =
  (typeof UpdateWorkItemBodyType)[keyof typeof UpdateWorkItemBodyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateWorkItemBodyType = {
  Task: "Task",
  Epic: "Epic",
  Issue: "Issue",
} as const;
