/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type WorkItemType = (typeof WorkItemType)[keyof typeof WorkItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemType = {
  Feature: "Feature",
  Bug: "Bug",
  Enhancement: "Enhancement",
  Documentation: "Documentation",
  Task: "Task",
  Epic: "Epic",
  Test_Case: "Test Case",
  Issue: "Issue",
  User_Story: "User Story",
} as const;
