/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */

export type WorkItemStatus =
  (typeof WorkItemStatus)[keyof typeof WorkItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemStatus = {
  todo: "todo",
  "in-progress": "in-progress",
  review: "review",
  doing: "doing",
  completed: "completed",
  active: "active",
  new: "new",
  resolved: "resolved",
} as const;
