/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { WorkItemType } from "./workItemType";
import type { WorkItemStatus } from "./workItemStatus";

export interface WorkItem {
  id?: string;
  title?: string;
  description?: string;
  type?: WorkItemType;
  status?: WorkItemStatus;
  /**
   * @minimum 1
   * @maximum 4
   */
  priority?: number;
  assignedTo?: string;
  project?: string;
}
