/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import type { WorkItemCommentCreatedBy } from "./workItemCommentCreatedBy";
import type { CommentReaction } from "./commentReaction";

export interface WorkItemComment {
  /** Comment ID */
  id?: string;
  /** Comment text content */
  comment?: string;
  /** Reference to the work item ID */
  workItem?: string;
  /** User who created the comment */
  createdBy?: WorkItemCommentCreatedBy;
  /** Reactions on the comment */
  reactions?: CommentReaction[];
  /** When the comment was created */
  createdAt?: string;
  /** When the comment was last updated */
  updatedAt?: string;
}
