/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ApiResponse,
  GetApiReposParams,
  GetRepoFilesParams,
  GetRepoReadmeParams,
  PostApiReposBody,
} from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Get repositories By ProjectId
 */
export const getApiRepos = (
  params: GetApiReposParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/repos`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetApiReposQueryKey = (params?: GetApiReposParams) => {
  return [`/api/repos`, ...(params ? [params] : [])] as const;
};

export const getGetApiReposQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiRepos>>,
  TError = AxiosError<unknown>,
>(
  params: GetApiReposParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiRepos>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiReposQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiRepos>>> = ({
    signal,
  }) => getApiRepos(params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiRepos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiReposQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiRepos>>
>;
export type GetApiReposQueryError = AxiosError<unknown>;

export function useGetApiRepos<
  TData = Awaited<ReturnType<typeof getApiRepos>>,
  TError = AxiosError<unknown>,
>(
  params: GetApiReposParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiRepos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRepos>>,
          TError,
          Awaited<ReturnType<typeof getApiRepos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiRepos<
  TData = Awaited<ReturnType<typeof getApiRepos>>,
  TError = AxiosError<unknown>,
>(
  params: GetApiReposParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiRepos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiRepos>>,
          TError,
          Awaited<ReturnType<typeof getApiRepos>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiRepos<
  TData = Awaited<ReturnType<typeof getApiRepos>>,
  TError = AxiosError<unknown>,
>(
  params: GetApiReposParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiRepos>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repositories By ProjectId
 */

export function useGetApiRepos<
  TData = Awaited<ReturnType<typeof getApiRepos>>,
  TError = AxiosError<unknown>,
>(
  params: GetApiReposParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiRepos>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiReposQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create repository
 */
export const postApiRepos = (
  postApiReposBody: PostApiReposBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(`/api/repos`, postApiReposBody, options);
};

export const getPostApiReposMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiRepos>>,
    TError,
    { data: PostApiReposBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiRepos>>,
  TError,
  { data: PostApiReposBody },
  TContext
> => {
  const mutationKey = ["postApiRepos"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiRepos>>,
    { data: PostApiReposBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiRepos(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiReposMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiRepos>>
>;
export type PostApiReposMutationBody = PostApiReposBody;
export type PostApiReposMutationError = AxiosError<unknown>;

/**
 * @summary Create repository
 */
export const usePostApiRepos = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiRepos>>,
      TError,
      { data: PostApiReposBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiRepos>>,
  TError,
  { data: PostApiReposBody },
  TContext
> => {
  const mutationOptions = getPostApiReposMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get repository details by ID
 */
export const getGithubRepoDetails = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/repos/${id}`, options);
};

export const getGetGithubRepoDetailsQueryKey = (id?: string) => {
  return [`/api/repos/${id}`] as const;
};

export const getGetGithubRepoDetailsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGithubRepoDetails>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGithubRepoDetails>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGithubRepoDetailsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGithubRepoDetails>>
  > = ({ signal }) => getGithubRepoDetails(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGithubRepoDetails>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGithubRepoDetailsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGithubRepoDetails>>
>;
export type GetGithubRepoDetailsQueryError = AxiosError<void>;

export function useGetGithubRepoDetails<
  TData = Awaited<ReturnType<typeof getGithubRepoDetails>>,
  TError = AxiosError<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGithubRepoDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGithubRepoDetails>>,
          TError,
          Awaited<ReturnType<typeof getGithubRepoDetails>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGithubRepoDetails<
  TData = Awaited<ReturnType<typeof getGithubRepoDetails>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGithubRepoDetails>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGithubRepoDetails>>,
          TError,
          Awaited<ReturnType<typeof getGithubRepoDetails>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGithubRepoDetails<
  TData = Awaited<ReturnType<typeof getGithubRepoDetails>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGithubRepoDetails>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repository details by ID
 */

export function useGetGithubRepoDetails<
  TData = Awaited<ReturnType<typeof getGithubRepoDetails>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGithubRepoDetails>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGithubRepoDetailsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get repository branches by ID
 */
export const getRepoBranches = (
  id: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/repos/${id}/branches`, options);
};

export const getGetRepoBranchesQueryKey = (id?: string) => {
  return [`/api/repos/${id}/branches`] as const;
};

export const getGetRepoBranchesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRepoBranches>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRepoBranches>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRepoBranchesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRepoBranches>>> = ({
    signal,
  }) => getRepoBranches(id, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRepoBranches>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRepoBranchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRepoBranches>>
>;
export type GetRepoBranchesQueryError = AxiosError<void>;

export function useGetRepoBranches<
  TData = Awaited<ReturnType<typeof getRepoBranches>>,
  TError = AxiosError<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRepoBranches>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoBranches>>,
          TError,
          Awaited<ReturnType<typeof getRepoBranches>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoBranches<
  TData = Awaited<ReturnType<typeof getRepoBranches>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRepoBranches>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoBranches>>,
          TError,
          Awaited<ReturnType<typeof getRepoBranches>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoBranches<
  TData = Awaited<ReturnType<typeof getRepoBranches>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRepoBranches>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repository branches by ID
 */

export function useGetRepoBranches<
  TData = Awaited<ReturnType<typeof getRepoBranches>>,
  TError = AxiosError<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRepoBranches>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRepoBranchesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get repository files by ID
 */
export const getRepoFiles = (
  id: string,
  params: GetRepoFilesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/repos/${id}/files`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetRepoFilesQueryKey = (
  id?: string,
  params?: GetRepoFilesParams,
) => {
  return [`/api/repos/${id}/files`, ...(params ? [params] : [])] as const;
};

export const getGetRepoFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRepoFiles>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoFilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoFiles>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRepoFilesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRepoFiles>>> = ({
    signal,
  }) => getRepoFiles(id, params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRepoFiles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRepoFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRepoFiles>>
>;
export type GetRepoFilesQueryError = AxiosError<void>;

export function useGetRepoFiles<
  TData = Awaited<ReturnType<typeof getRepoFiles>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoFilesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoFiles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoFiles>>,
          TError,
          Awaited<ReturnType<typeof getRepoFiles>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoFiles<
  TData = Awaited<ReturnType<typeof getRepoFiles>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoFilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoFiles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoFiles>>,
          TError,
          Awaited<ReturnType<typeof getRepoFiles>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoFiles<
  TData = Awaited<ReturnType<typeof getRepoFiles>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoFilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoFiles>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repository files by ID
 */

export function useGetRepoFiles<
  TData = Awaited<ReturnType<typeof getRepoFiles>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoFilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoFiles>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRepoFilesQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get repository readme by ID
 */
export const getRepoReadme = (
  id: string,
  params: GetRepoReadmeParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.get(`/api/repos/${id}/readme`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetRepoReadmeQueryKey = (
  id?: string,
  params?: GetRepoReadmeParams,
) => {
  return [`/api/repos/${id}/readme`, ...(params ? [params] : [])] as const;
};

export const getGetRepoReadmeQueryOptions = <
  TData = Awaited<ReturnType<typeof getRepoReadme>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoReadmeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoReadme>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRepoReadmeQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRepoReadme>>> = ({
    signal,
  }) => getRepoReadme(id, params, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRepoReadme>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRepoReadmeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRepoReadme>>
>;
export type GetRepoReadmeQueryError = AxiosError<void>;

export function useGetRepoReadme<
  TData = Awaited<ReturnType<typeof getRepoReadme>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoReadmeParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoReadme>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoReadme>>,
          TError,
          Awaited<ReturnType<typeof getRepoReadme>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoReadme<
  TData = Awaited<ReturnType<typeof getRepoReadme>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoReadmeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoReadme>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRepoReadme>>,
          TError,
          Awaited<ReturnType<typeof getRepoReadme>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRepoReadme<
  TData = Awaited<ReturnType<typeof getRepoReadme>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoReadmeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoReadme>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get repository readme by ID
 */

export function useGetRepoReadme<
  TData = Awaited<ReturnType<typeof getRepoReadme>>,
  TError = AxiosError<void>,
>(
  id: string,
  params: GetRepoReadmeParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getRepoReadme>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRepoReadmeQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
