/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Kanban API
 * API for Kanban project management system
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ApiResponse,
  PostApiAuthSigninBody,
  PostApiAuthSignupBody,
} from "../../types";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary Sign in user
 */
export const postApiAuthSignin = (
  postApiAuthSigninBody: PostApiAuthSigninBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(`/api/auth/signin`, postApiAuthSigninBody, options);
};

export const getPostApiAuthSigninMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthSignin>>,
    TError,
    { data: PostApiAuthSigninBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthSignin>>,
  TError,
  { data: PostApiAuthSigninBody },
  TContext
> => {
  const mutationKey = ["postApiAuthSignin"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthSignin>>,
    { data: PostApiAuthSigninBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthSignin(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthSigninMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthSignin>>
>;
export type PostApiAuthSigninMutationBody = PostApiAuthSigninBody;
export type PostApiAuthSigninMutationError = AxiosError<unknown>;

/**
 * @summary Sign in user
 */
export const usePostApiAuthSignin = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthSignin>>,
      TError,
      { data: PostApiAuthSigninBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthSignin>>,
  TError,
  { data: PostApiAuthSigninBody },
  TContext
> => {
  const mutationOptions = getPostApiAuthSigninMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Sign up new user
 */
export const postApiAuthSignup = (
  postApiAuthSignupBody: PostApiAuthSignupBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ApiResponse>> => {
  return axios.default.post(`/api/auth/signup`, postApiAuthSignupBody, options);
};

export const getPostApiAuthSignupMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthSignup>>,
    TError,
    { data: PostApiAuthSignupBody },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthSignup>>,
  TError,
  { data: PostApiAuthSignupBody },
  TContext
> => {
  const mutationKey = ["postApiAuthSignup"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthSignup>>,
    { data: PostApiAuthSignupBody }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthSignup(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthSignupMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthSignup>>
>;
export type PostApiAuthSignupMutationBody = PostApiAuthSignupBody;
export type PostApiAuthSignupMutationError = AxiosError<unknown>;

/**
 * @summary Sign up new user
 */
export const usePostApiAuthSignup = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthSignup>>,
      TError,
      { data: PostApiAuthSignupBody },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthSignup>>,
  TError,
  { data: PostApiAuthSignupBody },
  TContext
> => {
  const mutationOptions = getPostApiAuthSignupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
