import mongoose, { Schema, model, models } from 'mongoose';
import bcrypt from 'bcryptjs';

const UserSchema = new Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true,
    maxLength: [100, 'Name cannot exceed 100 characters'],
    index: true
  },
  email: {
    type: String,
    unique: true,
    required: [true, 'Email is required'],
    trim: true,
    lowercase: true,
    index: true,
    match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/, 'Please enter a valid email']
  },
  password: {
    type: String,
    required: [true, 'Password is required'],
    minLength: [6, 'Password must be at least 6 characters'],
    select: false // Don't include password in queries by default
  },
  role: {
    type: String,
    enum: ['user', 'admin', 'moderator'],
    default: 'user',
    index: true
  },
  isFromEMS: {
    type: Boolean,
    default: false,
    index: true
  },
  autoGeneratedPassword: {
    type: Boolean,
    default: false
  },
  
  // GitHub integration fields
  githubUsername: {
    type: String,
    default: null,
    trim: true,
    sparse: true,
    index: true
  },
  githubAccessToken: {
    type: String,
    default: null,
  },
  githubId: {
    type: Number,
    default: null,
    sparse: true,
    index: true
  },
  
  // Global user ID for EMS integration
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    default: null,
    sparse: true,
    index: true
  },
  
  // Profile fields
  avatar: {
    type: String,
    default: null
  },
  bio: {
    type: String,
    maxLength: [500, 'Bio cannot exceed 500 characters'],
    trim: true
  },
  location: {
    type: String,
    maxLength: [100, 'Location cannot exceed 100 characters'],
    trim: true
  },
  website: {
    type: String,
    trim: true
  },
  
  // Account status
  isActive: {
    type: Boolean,
    default: true,
    index: true
  },
  lastLoginAt: {
    type: Date,
    default: null
  },
  
  // Password reset
  resetPasswordToken: {
    type: String,
    default: null,
    select: false
  },
  resetPasswordExpires: {
    type: Date,
    default: null,
    select: false
  }
}, { 
  timestamps: true,
  toJSON: { 
    virtuals: true,
    transform: function(doc, ret) {
      delete ret.password;
      delete ret.resetPasswordToken;
      delete ret.resetPasswordExpires;
      return ret;
    }
  },
  toObject: { virtuals: true }
});

// Compound indexes for performance
UserSchema.index({ email: 1, isActive: 1 });
UserSchema.index({ role: 1, isFromEMS: 1 });
UserSchema.index({ githubUsername: 1, githubId: 1 });
UserSchema.index({ userId: 1, isFromEMS: 1 });

// Virtual for full name formatting
UserSchema.virtual('displayName').get(function() {
  return this.name || this.email.split('@')[0];
});

// Virtual for GitHub integration status
UserSchema.virtual('hasGitHubIntegration').get(function() {
  return !!(this.githubAccessToken && this.githubUsername);
});

// Pre-save middleware for password hashing
UserSchema.pre('save', async function(next) {
  // Only hash the password if it has been modified (or is new)
  if (!this.isModified('password')) return next();
  
  try {
    // Hash password with cost of 12
    const hashedPassword = await bcrypt.hash(this.password, 12);
    this.password = hashedPassword;
    next();
  } catch (error) {
    next(error);
  }
});

// Pre-save middleware for email normalization
UserSchema.pre('save', function(next) {
  if (this.isModified('email')) {
    this.email = this.email.toLowerCase().trim();
  }
  if (this.isModified('name')) {
    this.name = this.name.trim();
  }
  next();
});

// Instance methods
UserSchema.methods.comparePassword = async function(candidatePassword) {
  return bcrypt.compare(candidatePassword, this.password);
};

UserSchema.methods.updateLastLogin = function() {
  this.lastLoginAt = new Date();
  return this.save();
};

UserSchema.methods.generateResetToken = function() {
  const crypto = require('crypto');
  const resetToken = crypto.randomBytes(32).toString('hex');
  
  this.resetPasswordToken = crypto
    .createHash('sha256')
    .update(resetToken)
    .digest('hex');
  
  this.resetPasswordExpires = Date.now() + 10 * 60 * 1000; // 10 minutes
  
  return resetToken;
};

UserSchema.methods.clearResetToken = function() {
  this.resetPasswordToken = null;
  this.resetPasswordExpires = null;
  return this.save();
};

UserSchema.methods.connectGitHub = function(githubData) {
  this.githubUsername = githubData.githubUsername;
  this.githubAccessToken = githubData.githubAccessToken;
  this.githubId = githubData.githubId;
  return this.save();
};

UserSchema.methods.disconnectGitHub = function() {
  this.githubUsername = null;
  this.githubAccessToken = null;
  this.githubId = null;
  return this.save();
};

UserSchema.methods.toSafeObject = function() {
  const userObject = this.toObject();
  delete userObject.password;
  delete userObject.resetPasswordToken;
  delete userObject.resetPasswordExpires;
  return userObject;
};

// Static methods
UserSchema.statics.findByEmail = function(email) {
  return this.findOne({ email: email.toLowerCase().trim() });
};

UserSchema.statics.findByGithubId = function(githubId) {
  return this.findOne({ githubId });
};

UserSchema.statics.findByGithubUsername = function(githubUsername) {
  return this.findOne({ githubUsername: githubUsername.toLowerCase().trim() });
};

UserSchema.statics.findEMSUsers = function() {
  return this.find({ isFromEMS: true });
};

UserSchema.statics.findActiveUsers = function() {
  return this.find({ isActive: true });
};

UserSchema.statics.findByRole = function(role) {
  return this.find({ role });
};

UserSchema.statics.searchUsers = function(searchTerm, limit = 10) {
  const regex = new RegExp(searchTerm, 'i');
  return this.find({
    $or: [
      { name: regex },
      { email: regex },
      { githubUsername: regex }
    ],
    isActive: true
  }).limit(limit);
};

UserSchema.statics.findByUserId = function(userId) {
  return this.findOne({ userId });
};

const User = models.User || model('User', UserSchema);

export default User; 